name: EternalOptimization
version: '${version}'
main: eternalpolar.spigot.eternaloptimization.EternalOptimization
commands:
  eternaloptimization:
    aliases: [eo]
    description: The command of Eternal Optimization